---
title: "Capstone_EDA_Draft"
author: "Leah Hunt"
date: "9/23/2020"
output: html_document
---

```{r}
library(lubridate)
library(ggplot2)
library("tidyverse")
library("cluster")
library("factoextra")
library(tidyr)
data <- read.table("economicData.txt", header = TRUE)
```
```{r}
head(data)
```


Create a nice table to describe variables:
```{r}
date <- c("DATE", "", "Date on which observations were taken; reported as the first of the month")
dow <- c("DOW", "Dollars", "Gives the value of the DOW Jones as of closing on a particular date")
netexp <- c("NETEXP", "Billions of dollars", "US exports minus US imports")
unemployment <- c("unemployment", "", "US unemployment rate (unemployed/total people)")
oil <- c("oil", "dollars/barrel", "Price of oil; based out of West Texas")
gold <- c("gold", "dollers/ounce", "Price of gold; based on London Bullion Market")
cpi <- c("cpi", "relative to 1982-1984" , "Consumer price index; amount that 1 dollar is worth in 1982-1984 dollars")
ffr <- c("ffr", "", "Federal Funds Rate  set by the Federal Reserve")
gdp <- c("gdp", "Billions of 2012 adjusted dollars", "Real Gross Domestic Product")
cc <- c("consumer_confidence", "", "Consumer confidence using the University of Michigan Consumer Sentiment index with 1966 as the base year")

varExplanations <- matrix(c(date, dow, netexp, unemployment, oil, gold, cpi, ffr, gdp, cc), ncol = 3, byrow = TRUE)
varExplanations <- as.data.frame(varExplanations)
#varExplanations
colnames(varExplanations) <- c("Variable Name", "Unit", "Description")
knitr::kable(varExplanations, 
             caption = "Explanation of the meanings of all variables",
             align = c('c', rep('l', 2))) %>%
kableExtra::kable_styling(bootstrap_options = c("striped", "condensed"),
                          font_size = 9, latex_options = "HOLD_position")
```




```{r}
for(i in c(5, 8:15)){
  plot <- ggplot(aes(x = ymd(DATE), y = data[,i]), data = data) +
    geom_point() +
    geom_smooth() + 
    ylab(colnames(data)[i])
  print(plot)
}

```


Random clustering stuff that you can ignore


```{r}
fviz_nbclust(na.omit(data)[,c(5, 8:15)], kmeans, method="wss")
```



```{r}
k2<-stats::kmeans(na.omit(data)[,c(5, 8:15)], centers=3, nstart=25)
results <- data.frame(DATE = na.omit(data)$DATE, cluster = k2$cluster)
plot(x = ymd(results$DATE), y = results$cluster, pch = 20)
```


```{r}
k2<-stats::kmeans(na.omit(data)[,c(5, 8:15)], centers=4, nstart=25)
results <- data.frame(DATE = na.omit(data)$DATE, cluster = k2$cluster)
plot(x = ymd(results$DATE), y = results$cluster, pch = 20)
```


Slightly more interesting: considers differences between days instead of nominal values

```{r}
dataDiffs <- data
for(col in 2:ncol(data)){
  for(row in 2:nrow(data)){
    dataDiffs[row, col] <- data[row, col] - data[row-1, col]
  }
}
```

```{r}
dataDiffs <- na.omit(dataDiffs)
```

```{r}
for(i in c(5, 8:15)){
  plot <- ggplot(aes(x = ymd(DATE), y = dataDiffs[,i]), data = dataDiffs) +
    geom_point() +
    geom_smooth() + 
    ylab(colnames(dataDiffs)[i])
  print(plot)
}

```

Not as interesting; just me playing around with clustering again (possibly interpretable)
```{r}
fviz_nbclust(dataDiffs[,c(5, 8:15)], kmeans, method="wss")
```

```{r}
for(x in 4:5){
k2<-stats::kmeans(dataDiffs[,c(5, 8:15)], centers=x, nstart=25)
results <- data.frame(DATE = dataDiffs$DATE, cluster = k2$cluster)
plot(x = ymd(results$DATE), y = results$cluster, pch = 20)
plot(x = ymd(results$DATE[1:173]), y = results$cluster[1:173], pch = 20)
plot(x = ymd(results$DATE[173:273]), y = results$cluster[173:273], pch = 20)
plot(x = ymd(results$DATE[273:373]), y = results$cluster[273:373], pch = 20)
plot(x = ymd(results$DATE[373:473]), y = results$cluster[373:473], pch = 20)

}
```



